# Generated by Django 3.2.18 on 2023-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
